skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
latch = "8QFtCzFQDdQNWoz8XX4zYzPixf7L3vaHLe1Pj67zWFMz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
